version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mysql_db_docker
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 9960844980&Ss
      MYSQL_DATABASE: SCM

    volumes: 
     - ./mysql_data:/var/lib/mysql


  phpmyadmin: 
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8081:80"
    environment:
       
       